/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.presentation;

import java.awt.Color;
import java.util.List;

import com.google.gson.Gson;

import co.unicauca.microkernel.business.DeliveryService;
import co.unicauca.microkernel.business.ProductService;
import co.unicauca.microkernel.common.entities.Cerveza;
import co.unicauca.microkernel.common.entities.Medicion;
import co.unicauca.microkernel.infra.Publisher;

/**
 *
 * @author ahurtado
 */

public class GUISendProduct extends javax.swing.JFrame {

    private ProductService productService;
    private DeliveryService deliveryService;
    List<Cerveza> products;
    Publisher publisher;

    /**
     * Creates new form GUISendProduct
     */
    public GUISendProduct() {
        initComponents();
        productService = new ProductService();
        publisher = new Publisher();
        products = productService.getAll();
        /*
         * aqui añadia al jcombobox
         * for (int index = 0; index < products.size(); index++) {
         * jComboBox1.addItem(products.get(index).getName());
         * }
         */
        txtEstado.setEnabled(false);
        txtEstado.setText("...");
        jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreComercial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPesoCerveza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdCerveza = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proceso de la cerveza");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        jLabel6.setText("Nombre Comercial");

        jLabel2.setText("Digite el id de cerveza");

        jLabel3.setText("Digite el peso en Gramos");

        jLabel4.setText("Indique el código de la marca");

        jLabel5.setText("Estado del proceso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtPesoCerveza,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 151,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(23, 23, 23))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                124,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                124,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(97, 97, 97)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtNombreComercial,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                151,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtIdCerveza,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                151,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addContainerGap(32, Short.MAX_VALUE)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtIdCerveza, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPesoCerveza, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jButton1.setText("Calcular Medicion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Enviar Notificacion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Cerveza selectedProduct = products.get(this.jComboBox1.getSelectedIndex());
        // Cerveza cerveza = cerveza.getName()

        Cerveza objCerveza = new Cerveza();
        objCerveza.setName(txtNombreComercial.getText());
        objCerveza.setProductId(Integer.parseInt(txtIdCerveza.getText()));
        objCerveza.setWeight(Double.parseDouble(txtPesoCerveza.getText()));

        Medicion deliveryEntity = new Medicion(objCerveza,
                Double.parseDouble(txtPesoCerveza.getText()),
                txtMarca.getText());
        try {
            deliveryService = new DeliveryService();
            double cost = deliveryService.calculateDeliveryCost(deliveryEntity);

            if (cost == 1) {
                txtEstado.setText("Aprobado");
                txtEstado.setBackground(Color.GREEN);
                jButton2.setVisible(true);
            } else {

                txtEstado.setText("No Aprobado");
                txtEstado.setBackground(Color.red);
            }

            // txtEstado.setText(""+cost);
        } catch (Exception exception) {
            System.out.println("No fue posible calcular si fue aprobado. " + exception.getMessage());
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Cerveza selectedProduct = products.get(this.jComboBox1.getSelectedIndex());
        Cerveza objCerveza = new Cerveza();
        txtEstado.setText("Aprobado");
        objCerveza.setName(txtNombreComercial.getText());
        objCerveza.setProductId(Integer.parseInt(txtIdCerveza.getText()));
        objCerveza.setWeight(Double.parseDouble(txtPesoCerveza.getText()));
        Gson gson = new Gson();
        String msgJson = gson.toJson(objCerveza);
        publisher.publish(msgJson);
        jButton2.setVisible(false);

    }// GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdCerveza;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombreComercial;
    private javax.swing.JTextField txtPesoCerveza;
    // End of variables declaration//GEN-END:variables

}
